### ISSUE TITLE
Latest emoji library 3.3.0 yields syntax error

### ISSUE THREAD

**Issue by klauso** [NodeBB/nodebb-plugin-emoji#35]
When I activate v3.3.0 of this library in my nodebb installation 1.13.2, I get the log messages below and the plugin isn't activated. The syntax error is not obviously related to the emoji library, but it disappears when I disable the plugin.

```
Apr 07 11:40:34 2020-04-07T09:40:34.353Z [4567/1111] - warn: [plugins] Unable to parse library for: nodebb-plugin-emoji
Apr 07 11:40:34 2020-04-07T09:40:34.355Z [4567/1111] - error: /run/nodebb/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
Apr 07 11:40:34 } catch {
Apr 07 11:40:34 ^
Apr 07 11:40:34
Apr 07 11:40:34 SyntaxError: Unexpected token {
Apr 07 11:40:34 at createScript (vm.js:80:10)
Apr 07 11:40:34 at Object.runInThisContext (vm.js:139:10)
Apr 07 11:40:34 at Module._compile (module.js:617:28)
Apr 07 11:40:34 at Object.Module._extensions..js (module.js:664:10)
Apr 07 11:40:34 at Module.load (module.js:566:32)
Apr 07 11:40:34 at tryModuleLoad (module.js:506:12)
Apr 07 11:40:34 at Function.Module._load (module.js:498:3)
Apr 07 11:40:34 at Module.require (module.js:597:17)
Apr 07 11:40:34 at require (internal/module.js:11:18)
Apr 07 11:40:34 at Object.<anonymous> (/run/nodebb/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```

**Comment by pitaj** [comment]
What version of Node.js are you on? You probably need to upgrade.

**Comment by pitaj** [comment]
Closed for inactivity
