### ISSUE TITLE
error after upgrading NodeBB 1.19.2

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/nodebb-plugin-emoji#51]
after upgrading to NodeBB 1.19.2 we got 100s of this error in the log:

```
2022-02-11T02:49:28.984Z [4567/24661] - [31merror[39m: [emoji] Failed to retrieve data for parse ENOENT: no such file or directory, open '/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json' {"code":"ENOENT","errno":-2,"path":"/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json","stack":"Error: ENOENT: no such file or directory, open '/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json'","syscall":"open"}
2022-02-11T02:49:28.986Z [4567/24661] - [31merror[39m: [emoji] Failed to retrieve data for parse ENOENT: no such file or directory, open '/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json' {"code":"ENOENT","errno":-2,"path":"/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json","stack":"Error: ENOENT: no such file or directory, open '/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json'","syscall":"open"}
2022-02-11T02:49:29.022Z [4567/24661] - [31merror[39m: [emoji] Failed to retrieve data for parse ENOENT: no such file or directory, open '/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json' {"code":"ENOENT","errno":-2,"path":"/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json","stack":"Error: ENOENT: no such file or directory, open '/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json'","syscall":"open"}
2022-02-11T02:49:29.023Z [4567/24661] - [31merror[39m: [emoji] Failed to retrieve data for parse ENOENT: no such file or directory, open '/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json' {"code":"ENOENT","errno":-2,"path":"/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json","stack":"Error: ENOENT: no such file or directory, open '/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json'","syscall":"open"}
2022-02-11T02:49:29.024Z [4567/24661] - [31merror[39m: [emoji] Failed to retrieve data for parse ENOENT: no such file or directory, open '/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json' {"code":"ENOENT","errno":-2,"path":"/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json","stack":"Error: ENOENT: no such file or directory, open '/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json'","syscall":"open"}
2022-02-11T02:49:29.024Z [4567/24661] - [31merror[39m: [emoji] Failed to retrieve data for parse ENOENT: no such file or directory, open '/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json' {"code":"ENOENT","errno":-2,"path":"/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json","stack":"Error: ENOENT: no such file or directory, open '/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json'","syscall":"open"}
2022-02-11T02:49:29.025Z [4567/24661] - [31merror[39m: [emoji] Failed to retrieve data for parse ENOENT: no such file or directory, open '/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json' {"code":"ENOENT","errno":-2,"path":"/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json","stack":"Error: ENOENT: no such file or directory, open '/home/fsuzer/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json'","syscall":"open"}

```

then, we reset the emoji plugin and rebuild the forum, normal emojis came back but ASCII characters are still not working, and the error above is gone and we have this error:

```
2022-02-11T02:52:32.682Z [4569/24935] - [31merror[39m: [plugins] Error executing 'static:app.load' in plugin 'nodebb-plugin-emoji'
TypeError: Config.global.get is not a function
    at Object.Config.user.get (/home/fsuzer/nodebb/node_modules/nodebb-plugin-shoutbox/lib/config.js:107:64)
    at Object.Shoutbox.settings.filterUserGetSettings [as method] (/home/fsuzer/nodebb/node_modules/nodebb-plugin-shoutbox/library.js:100:27)
    at fireMethod (/home/fsuzer/nodebb/src/plugins/hooks.js:137:25)
    at Object.fireFilterHook [as filter] (/home/fsuzer/nodebb/src/plugins/hooks.js:168:18)
    at Hooks.fire (/home/fsuzer/nodebb/src/plugins/hooks.js:105:49)
    at Object.wrapperCallback [as fire] (/home/fsuzer/nodebb/src/promisify.js:46:11)
    at onSettingsLoaded (/home/fsuzer/nodebb/src/user/settings.js:39:36)
    at User.getSettings (/home/fsuzer/nodebb/src/user/settings.js:15:17)
    at Object.wrapperCallback [as getSettings] (/home/fsuzer/nodebb/src/promisify.js:46:11)
    at Object.plugin.filterConfigGet [as method] (/home/fsuzer/nodebb/node_modules/nodebb-plugin-soundpack-default/index.js:14:34)

```

**Comment by barisusakli** [comment]
The shoutbox error is another issue, i will fix that in the shoutbox plugin
