### ISSUE TITLE
ASCII characters not turning into emojis

### ISSUE THREAD

**Issue by bullet64** [NodeBB/nodebb-plugin-emoji#52]
After last update to nodebb v1.19.2 ASCII characters not turning into emojis.

I found this in logs.

```
2022-02-15T20:04:09.766Z [4568/49410] - ^[[31merror^[[39m: [plugins] Error executing 'static:app.load' in plugin 'nodebb-plugin-emoji'
TypeError: Cannot read properties of undefined (reading 'get')
    at Object.plugin.getConfig [as method] (/home/user_radforum/nodebb/node_modules/nodebb-plugin-recent-cards/library.js:68:26)
    at fireMethod (/home/user_radforum/nodebb/src/plugins/hooks.js:137:25)
    at Object.fireFilterHook [as filter] (/home/user_radforum/nodebb/src/plugins/hooks.js:168:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Hooks.fire (/home/user_radforum/nodebb/src/plugins/hooks.js:105:17)
    at async apiController.loadConfig (/home/user_radforum/nodebb/src/controllers/api.js:116:9)
    at async Object.getBaseUrl (/home/user_radforum/nodebb/node_modules/nodebb-plugin-emoji/build/lib/base-url.js:7:30)
    at async init (/home/user_radforum/nodebb/node_modules/nodebb-plugin-emoji/build/lib/index.js:40:21)
    at async Object.fireStaticHook [as static] (/home/user_radforum/nodebb/src/plugins/hooks.js:209:5)
    at async Hooks.fire (/home/user_radforum/nodebb/src/plugins/hooks.js:105:17)
```

My active plugins

```
2022-02-15T20:24:58.144Z [4568/49537] - verbose: [minifier] utilizing a maximum of 3 additional threads
Active plugins:
	* nodebb-plugin-2factor@3.0.4 (installed, enabled)
	* nodebb-plugin-composer-default@7.0.20 (installed, enabled)
	* nodebb-plugin-dbsearch@5.1.1 (installed, enabled)
	* nodebb-plugin-emoji@3.5.12 (installed, enabled)
	* nodebb-plugin-emoji-android@2.0.5 (installed, enabled)
	* nodebb-plugin-emoji-apple@2.0.5 (installed, enabled)
	* nodebb-plugin-markdown@9.0.5 (installed, enabled)
	* nodebb-plugin-mentions@3.0.4 (installed, enabled)
	* nodebb-plugin-ns-embed@4.0.0 (installed, enabled)
	* nodebb-plugin-question-and-answer@0.12.20 (installed, enabled)
	* nodebb-plugin-recent-cards@2.0.20 (installed, enabled)
	* nodebb-plugin-soundpack-default@2.0.1 (installed, disabled)
	* nodebb-plugin-spam-be-gone@0.7.12 (installed, enabled)
	* nodebb-plugin-twitter@0.1.0 (installed, enabled)
	* nodebb-rewards-essentials@0.2.1 (installed, enabled)
	* nodebb-theme-lavender@5.3.2 (installed, disabled)
	* nodebb-theme-persona@11.3.38 (installed, enabled)
	* nodebb-theme-slick@1.4.23 (installed, disabled)
	* nodebb-theme-vanilla@12.1.17 (installed, disabled)
	* nodebb-widget-essentials@5.0.7 (installed, enabled)
```

**Comment by barisusakli** [comment]
Please try with emoji  v3.5.13

**Comment by bullet64** [comment]
it seems to be working ;)

![grafik](https://user-images.githubusercontent.com/10364233/154195238-1ea3c5cb-39c6-4f26-b611-4377838de635.png)
